static const Item rootItems[]={IT_SEP("INAZUMA ELEVEN"),IT_CHEAT("Game / compatibility status",CH_STATUS,"Confirm the Title ID profile before edits."),IT_FOLDER("Currency",F_CURRENCY),IT_FOLDER("Inventory",F_INVENTORY),IT_FOLDER("Players / roster",F_PLAYERS),IT_FOLDER("IE3 unlocks",F_UNLOCKS),IT_SEP("SYSTEM"),IT_FOLDER("Tools",F_TOOLS),IT_FOLDER("Settings",F_SETTINGS)};
static const Item currencyItems[]={IT_CHEAT("Max money + friendship/passion",CH_CURRENCY,"One-shot save editor. Back up first."),IT_CHEAT("All Galaxy coins x999",CH_COINS,"Galaxy only.")};
static const Item inventoryItems[]={IT_CHEAT("Owned items/techniques x99",CH_ITEMS,"Sets existing quantities."),IT_CHEAT("Owned equipment x99",CH_EQUIPMENT,"Sets existing quantities.")};
static const Item playerItems[]={IT_FOLDER("IE3 player editor",F_PLAYER_EDITOR),IT_CHEAT("Roster Level 99 after match",CH_LEVEL99,"Published experience editor."),IT_CHEAT("Roster max stats",CH_STATS,"Published stat editor."),IT_CHEAT("Experimental Level 255",CH_LEVEL255,"Chrono Stones and Galaxy only.")};
static const Item playerEditorItems[]={IT_CHEAT("Choose roster slot",CH_PLAYER_SLOT,"Enter a slot from 1 to 100."),IT_CHEAT("Edit selected experience",CH_PLAYER_EXP,"Edit raw experience for the selected slot, from 0 to 9999999."),IT_CHEAT("Max selected player stats",CH_PLAYER_MAX,"Applies the published max-stat layout to only the selected IE3 roster slot.")};
static const Item unlockItems[]={IT_CHEAT("Unlock Secret flag",CH_SECRET,"Published IE3 Secret flag."),IT_CHEAT("Infinite match timer",CH_TIMER,"Continuous pointer-based timer code."),IT_CHEAT("Have all maps",CH_MAPS,"IE3 map item flags."),IT_CHEAT("Have all tickets",CH_TICKETS,"IE3 ticket item flags."),IT_CHEAT("All tokens x99",CH_TOKENS,"IE3 tokens."),IT_CHEAT("Old pin badge x99",CH_BADGE,"IE3 old pin badge.")};
static const Item toolsItems[]={IT_TOOL("Cheat Search",T_SEARCH,"Search RAM."),IT_TOOL("RAM Dumper",T_RAMDUMP,"Dump RAM."),IT_TOOL("Hex Editor",T_HEXEDIT,"Edit RAM."),IT_TOOL("About",T_ABOUT,"Version and credits.")};
static const Item settingsItems[]={IT_CHEAT("Change Theme",CH_CFG_THEME,"Change colours."),IT_CHEAT("Language",CH_CFG_LANG,"Cycle language."),IT_CHEAT("Toggle notifications",CH_CFG_TOAST,"Toggle notifications."),IT_CHEAT("Auto-fill Tracker",CH_CFG_AUTOFILL,"Engine setting."),IT_CHEAT("Quick Menu hotkey",CH_CFG_QMKEY,"Change hotkey."),IT_CHEAT("Hotkey 1",CH_CFG_HK1,"Engine setting."),IT_CHEAT("Hotkey 2",CH_CFG_HK2,"Engine setting."),IT_CHEAT("Reset hotkeys",CH_CFG_HKRESET,"Restore defaults.")};
#define FCOUNT(a)(int)(sizeof(a)/sizeof((a)[0]))
static const Folder folders[NUM_FOLDERS]={{"Inazuma Eleven",rootItems,FCOUNT(rootItems)},{"Currency",currencyItems,FCOUNT(currencyItems)},{"Inventory",inventoryItems,FCOUNT(inventoryItems)},{"Players / roster",playerItems,FCOUNT(playerItems)},{"IE3 player editor",playerEditorItems,FCOUNT(playerEditorItems)},{"IE3 unlocks",unlockItems,FCOUNT(unlockItems)},{"Tools",toolsItems,FCOUNT(toolsItems)},{"Settings",settingsItems,FCOUNT(settingsItems)}};
